export const HELLO_WORLD = "HELLO_WORLD";

// INPUT CHANGES
export const CHANGE_MONETARY_INPUT = "CHANGE_MONETARY_INPUT";

export const CHANGE_SELECTED_CURRENCY_CODE = "CHANGE_SELECTED_CURRENCY_CODE";

export const OPEN_CURRENCY_CODE_SELECTOR = "OPEN_CURRENCY_CODE_SELECTOR";
export const CLOSE_CURRENCY_CODE_SELECTOR = "CLOSE_CURRENCY_CODE_SELECTOR";

export const FETCH_LATEST_EXCHANGE_RATES = "FETCH_LATEST_EXCHANGE_RATES";
export const FETCH_LATEST_EXCHANGE_RATES_FAILED =
  "FETCH_LATEST_EXCHANGE_RATES_FAILED";
export const FETCH_LATEST_EXCHANGE_RATES_SUCCESS =
  "FETCH_LATEST_EXCHANGE_RATES_SUCCESS";
