export const HELLO_WORLD = "HELLO_WORLD";

// INPUT CHANGES
export const CHANGE_MONETARY_INPUT = "CHANGE_MONETARY_INPUT";

export const CHANGE_SELECTED_CURRENCY_CODE = "CHANGE_SELECTED_CURRENCY_CODE";
